export const REQUEST_ERROR_MESSAGES = 'REQUEST_ERROR_MESSAGES';
export const RECEIVE_ERROR_MESSAGES = 'RECEIVE_ERROR_MESSAGES';
export const RECEIVE_NEW_ERROR_MESSAGES = 'RECEIVE_NEW_ERROR_MESSAGES';
export const RECEIVE_ERROR_MESSAGE_ERROR = 'RECEIVE_ERROR_MESSAGE_ERROR';
export const TOGGLE_ERROR_STREAM = 'TOGGLE_ERROR_STREAM';
export const SET_ACTIVE_ERROR_MESSAGE = 'SET_ACTIVE_ERROR_MESSAGE';
export const CLEAR_SERVER_RENDERED = 'CLEAR_SERVER_RENDERED';