export const SET_PAGE = 'SET_PAGE';

export const REQUEST_AUDIT_MESSAGES = 'REQUEST_AUDIT_MESSAGES';
export const RECEIVE_AUDIT_MESSAGES = 'RECEIVE_AUDIT_MESSAGES';
export const RECEIVE_NEW_AUDIT_MESSAGES = 'RECEIVE_NEW_AUDIT_MESSAGES';
export const RECEIVE_AUDIT_MESSAGE_ERROR = 'RECEIVE_AUDIT_MESSAGE_ERROR';