export const REQUEST_ENDPOINTS = 'REQUEST_ENDPOINTS';
export const RECEIVE_ENDPOINTS = 'RECEIVE_ENDPOINTS';
export const RECEIVE_ENDPOINTS_ERROR = 'RECEIVE_ENDPOINTS_ERROR';
export const TOGGLE_HEARTBEAT_STREAM = 'TOGGLE_HEARTBEAT_STREAM';
export const RECEIVE_HEARTBEATS = 'RECEIVE_HEARTBEATS';
export const RECEIVE_ENDPOINT = 'RECEIVE_ENDPOINT';
export const CLEAR_SERVER_RENDERED = 'CLEAR_SERVER_RENDERED';